# Two-context source build for tomvaisbort/unpackerr (enhanced fork).
# Context layout: ./unpackerr (repo) + ./xtractr (sibling checkout), so the
# go.mod "replace golift.io/xtractr => ../xtractr" resolves /src/../xtractr.
#
# STANDALONE as of the 2026-09-11 upstream merge (f852cdc0): it used to be
# generated by sed/python from unpackerr/init/docker/Dockerfile, but upstream
# DELETED that path (moved to repo-root Dockerfile + init/docker/Dockerfile.goreleaser).
# Do not regenerate - edit this file, and re-stage sources around it.
FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS builder

# Node: go generate ./frontend runs npm ci + vite for the embedded SPA (upstream,
# 2026-09-27 merge; mirrors the repo-root Dockerfile).
RUN apk add --no-cache git nodejs npm

COPY xtractr /xtractr
WORKDIR /src
COPY unpackerr/main.go unpackerr/go.mod unpackerr/go.sum ./
RUN go mod download
COPY unpackerr/frontend/package.json unpackerr/frontend/package-lock.json ./frontend/
RUN npm ci --prefix frontend
COPY unpackerr/pkg pkg
COPY unpackerr/examples examples
COPY unpackerr/init/config init/config
COPY unpackerr/frontend frontend
RUN go generate ./...

ARG TARGETOS
ARG TARGETARCH
ARG BUILD_DATE
ARG BRANCH
ARG VERSION
ARG ITERATION
ARG COMMIT

ENV GOFLAGS="-trimpath -mod=readonly -modcacherw"
ENV GOOS=${TARGETOS}
ENV GOARCH=${TARGETARCH}

RUN go build -o /tmp/unpackerr -tags osusergo,netgo \
    -ldflags "-w -s -X \"golift.io/version.Branch=${BRANCH} (${COMMIT})\" \
    -X \"golift.io/version.BuildDate=${BUILD_DATE}\" \
    -X \"golift.io/version.BuildUser=docker\" \
    -X \"golift.io/version.Revision=${ITERATION}\" \
    -X \"golift.io/version.Version=${VERSION}\""

FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

ARG TARGETOS
ARG TARGETARCH
ARG BUILD_DATE
ARG COMMIT
ARG VERSION
ARG ITERATION
ARG LICENSE=MIT
ARG SOURCE_URL=http://github.com/golift/application-builder
ARG DESC=application-builder
ARG VENDOR=golift
ARG AUTHOR=golift
# Build-time metadata as defined at https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="Unpackerr" \
      org.opencontainers.image.documentation="https://unpackerr.zip" \
      org.opencontainers.image.description="${DESC}" \
      org.opencontainers.image.url="${SOURCE_URL}" \
      org.opencontainers.image.revision="${COMMIT}" \
      org.opencontainers.image.source="${SOURCE_URL}" \
      org.opencontainers.image.vendor="${VENDOR}" \
      org.opencontainers.image.authors="${AUTHOR}" \
      org.opencontainers.image.architecture="${TARGETOS} ${TARGETARCH}" \
      org.opencontainers.image.licenses="${LICENSE}" \
      org.opencontainers.image.version="${VERSION}-${ITERATION}"

COPY --from=builder /tmp/unpackerr /unpackerr
# Make sure we have an ssl cert chain and timezone data.
# ffmpeg (enhanced fork): required to split APE/WV/M4A/WAV CUE albums.
# Dropping it does NOT fail the build - split_flac just goes silently dead.
RUN apk add --no-cache ca-certificates openssl tzdata curl jq ffmpeg

ENV TZ=UTC

EXPOSE 5656

ENTRYPOINT [ "/unpackerr" ]
